# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.full(10,np.nan)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
np.array([1,2,3]).size

3

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
"""python3 -c 'command'"""

"python3 -c 'command'"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
z = np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
z = np.arange(0,9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
z = np.array([1,2,0,0,4,0])
z[z!=0]

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3) #단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3,3,3))
#random : 0~1 
#randint : op1 ~ op2

array([[[0.37864277, 0.53403925, 0.23876589],
        [0.32272233, 0.23884315, 0.14748693],
        [0.00840849, 0.31798366, 0.64385967]],

       [[0.96039903, 0.31680715, 0.49496591],
        [0.85123602, 0.24834762, 0.60310516],
        [0.82737343, 0.12295344, 0.72188725]],

       [[0.44503886, 0.43524688, 0.87180794],
        [0.10748834, 0.68639334, 0.71385074],
        [0.00290895, 0.94638049, 0.29001057]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
z = np.random.random((10,10))
print(z)
print(f"min {z.min()}")
print(f"max {z.max()}")

[[0.52575219 0.65930365 0.58265626 0.83036988 0.35176546 0.18115807
  0.37171366 0.40925665 0.88613221 0.95178799]
 [0.79707792 0.7470403  0.90935497 0.64053781 0.92411204 0.32045854
  0.28496671 0.77969019 0.9239441  0.36614075]
 [0.21530468 0.71756391 0.28047591 0.35206807 0.52598229 0.40641985
  0.64758089 0.1957655  0.51354197 0.71084414]
 [0.40745662 0.02787447 0.7861609  0.7496996  0.24860021 0.1305782
  0.50193074 0.03920964 0.58991975 0.25491368]
 [0.91587219 0.8377681  0.77771575 0.71124143 0.49138674 0.58195284
  0.84112635 0.47001562 0.16970875 0.45090641]
 [0.28429483 0.62280695 0.00352386 0.22896337 0.92139708 0.77181746
  0.42991326 0.08688898 0.21887254 0.91269047]
 [0.91848222 0.4827795  0.86963016 0.15347882 0.26809201 0.2476696
  0.02336288 0.74694194 0.25992469 0.32097507]
 [0.63929858 0.29657827 0.27370541 0.25643882 0.63633975 0.40788365
  0.74041673 0.63397432 0.29664412 0.5074074 ]
 [0.08230381 0.32619724 0.90840721 0.28711963 0.43548402 0.93846865
  0.26073639 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.random.random(30).mean()

0.598340566884303

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.full((5,5),1)
a[1:-1,1:-1] = 0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.full((5,5),0)
a[:1,:] = 1
a[:,:1] = 1
a[-1:,:] = 1
a[:,-1:] = 1
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
#non
#False
#False
#nand
#True
#False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
k = np.diag(np.arange(1,5),k=-1)
k

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
k = np.zeros((8,8))
k[::2,::2] = 1
k[1::2,1::2] = 1
k

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.tile(np.array([[1,0],[0,1]]),(4,4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
#Normalize : change the value between 0 and 1. keeping the ratio
z = np.random.randint(0,100,(5,5))
max = z.max()
min = z.min()
z = (z - min)/(max-min)
z

array([[0.40425532, 0.71276596, 0.13829787, 0.95744681, 0.5212766 ],
       [0.76595745, 0.23404255, 0.70212766, 0.89361702, 0.37234043],
       [0.41489362, 0.80851064, 0.34042553, 0.57446809, 0.85106383],
       [0.85106383, 0.57446809, 0.09574468, 0.90425532, 0.34042553],
       [1.        , 0.26595745, 0.        , 0.38297872, 0.89361702]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1)])
color 

/var/folders/cl/w3vvp74d6b95c0w799qxrb2w0000gn/T/ipykernel_2463/1539737010.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1)])


dtype([('r', 'u1'), ('g', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = np.random.random((5,3))
b = np.random.random((3,2))
a@b

array([[0.73406839, 0.83270891],
       [0.5249498 , 0.69885058],
       [0.75071095, 1.00956111],
       [0.78008832, 0.92910202],
       [0.5555139 , 0.68388511]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.array([x for x in range(-1,30)])
np.where((8>=a) & (a>=3)) #꼭 괄호로 묶어야함.


(array([4, 5, 6, 7, 8, 9]),)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
#from numpy import *
print(sum(range(5),-1))

9
9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.array([1,2,4,5])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
a = np.random.random(10)
np.round(a,0)

array([1., 0., 1., 0., 0., 1., 0., 0., 0., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [37]:
a = np.random.randint(1,30,20)
print(a)
b = np.random.randint(1,30,20)
print(b)
np.intersect1d(a,b)

[22 20  5 18  4 12  9  5 24 10 29 23 23 16 26 11 28 20 28 14]
[13 19 17  2  5 23 10 10 27 27 25 21 27 26 22  7 24  2  4  2]


array([ 4,  5, 10, 22, 23, 24, 26])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [41]:
np.sqrt(-1) #invalid
np.emath.sqrt(-4) #valid

/var/folders/cl/w3vvp74d6b95c0w799qxrb2w0000gn/T/ipykernel_2463/679516961.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) #invalid


2j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [53]:
print(np.datetime64('today'))
print(np.datetime64('today')-1)
print(np.datetime64('today')+1)

2023-07-11
2023-07-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [63]:
np.arange('2016-06-01','2016-07-01',dtype='datetime64')

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [70]:
a = np.random.random(10) * 100
print(np.floor(a))
print(np.ceil(a)-1)

[26. 89. 19. 34. 84. 47. 22.  8. 30. 20.]
[26. 89. 19. 34. 84. 47. 22.  8. 30. 20.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [73]:
np.array([x//5 for x in range(25)]).reshape(5,5)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [88]:
def gen():
    for i in range(10):
        yield i

np.fromiter(gen(),dtype='int') #fromiter: create array from iterable object like generater

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [87]:
a = np.random.random(10)
#a = [0.1,0.1,0.2,0.2,0.3,0.3,0.4,0.4,0.5,0.5]
while len(np.unique(a)) != 10:
    a = np.unique(a)
    a = np.append(a,np.random.random(10-len(a)))
a

array([0.1       , 0.2       , 0.3       , 0.4       , 0.5       ,
       0.55322919, 0.76045244, 0.60496437, 0.40641166, 0.84838894])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [89]:
a = np.random.random(10)
np.sort(a)

array([0.03972044, 0.08243832, 0.09019307, 0.1513601 , 0.28568849,
       0.29163947, 0.31242828, 0.68733091, 0.69997226, 0.87972047])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [91]:
a = np.random.random(10)
np.add.reduce(a) #reduce calculate axis

4.854968028211017

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [93]:
a = np.array([x for x in range(10)])
b= np.array([x for x in range(10)])
k = (a == b)
k

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)